### ISSUE TITLE
Allow to use ~/.ovh.conf file to setup provider

### ISSUE THREAD

**Issue by mcanevet** [terraform-providers/terraform-provider-ovh#10]
OVH provides an ovh-cli tool that stores the credentials in `~/.ovh.conf` in that format:
```
[default]
endpoint=ovh-eu

[ovh-eu]
application_key=<my_application_key>
application_secret=<my_application_secret>
consumer_key=<my_consumer_key>

[ovh-cli]
```
It would be great if the OVH provider could fetch credentials from this file.
For example:
```hcl
provider "ovh" {
  profile = "ovh-eu"
}
```
Juste like the aws providers allows:
```hcl
provider "aws" {
  profile = "my_profile"
}
```

**Comment by pvalois** [comment]
error is "profile ="
the correct syntax is : 
endpoint : "ovh-eu"
