### ISSUE TITLE
panic: interface conversion: error is *json.UnmarshalTypeError, not *ovh.APIError

### ISSUE THREAD

**Issue by kerwanp** [terraform-providers/terraform-provider-ovh#108]
### Terraform Version

Terraform v0.12.16
+ provider.aws v2.39.0
+ provider.helm v0.10.4
+ provider.kubernetes v1.10.0
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.ovh v0.5.0
+ provider.random v2.2.1
+ provider.template v2.1.2

### Affected Resource(s)

- ovh_domain_zone_record

### Terraform Configuration Files
```hcl
provider "ovh" {
  endpoint = "ovh-eu"
  application_key = "xxx"
  application_secret = "xxx"
  consumer_key = "xxx"
}

/*
 * Retreive the ovh_domain_zone object for the domain "group-bow.com"
 */
data "ovh_domain_zone" "group-bow" {
  name = "xxx.com"
}

#<<<<<<<<<<
# GRAFANA
#<<<<<<<<<<

/*
 * Retreive the service to get the external IP
 * The externalIP should be the DNS of the auto-generated ELB
 */
data "kubernetes_service" "grafana" {
  metadata {
    name = "prometheus-grafana"
    namespace = "monitoring"
  }
}

/*
 * Creates the CNAME OVH DNS record pointing to the ELB
 */
resource "ovh_domain_zone_record" "grafana" {
  zone = data.ovh_domain_zone.group-bow.name
  subdomain = "xxx.xxx"
  fieldtype = "CNAME"
  ttl = "0"
  target = "${data.kubernetes_service.grafana.load_balancer_ingress.0.hostname}."
}
```

### Debug Output
https://gist.github.com/kerwanp/35cf4fe8beb0113502d1d1500cdc2da9

### Panic Output
https://gist.github.com/kerwanp/35cf4fe8beb0113502d1d1500cdc2da9

### Expected Behavior
This should plan with the current state.

### Actual Behavior
`terraform plan` will just produce the error :
`Error: rpc error: code = Unavailable desc = transport is closing`

But `terraform plan -target=ovh_domain_zone_record.grafana` panic crash with the same error but with explicit log

### Steps to Reproduce

1. `terraform apply`, `terraform plan`, `terraform destroy`

**Comment by kerwanp** [comment]
After trying to destroy manually the resource by deleting the record on OVH and deleting the entry in `terraform.tfstate`.
I'm getting this error when trying to apply the plan :
```
Error: Failed to create OVH Record: json: cannot unmarshal number 5088060241 into Go struct field OvhDomainZoneRecord.id of type int
```

**Comment by yanndegat** [comment]
this is issue is fixed for the ovh_domain_zone_record

yet we'll keep it open as there may be other attributes in the provider which suffer the same issue

**Comment by yanndegat** [comment]
closing. will open new issue if same behaviour appears elsewhere
