### ISSUE TITLE
TF provider fails with unexpected EOF

### ISSUE THREAD

**Issue by mhl-lhc** [terraform-providers/terraform-provider-ovh#15]
Hi there,

Unfortunately, I am not able to use the OVH provider as per version 0.2.0.
Docker is up-to-date, Terraform is too and i'm running the official hashicorp/terraform:latest image.

Thanks for your help and work.

### Terraform Version
Terraform version: 0.11.2  a6008b8a48a749c7c167453b9cf55ffd572b9a5d

### Affected Resource(s)
- provider ovh
- resource "ovh_domain_zone_record"

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
provider "ovh" {
	endpoint = "ovh-eu"
	application_key = "xxx"
	application_secret = "xxx"
	consumer_key = "xxx"
}

resource "ovh_domain_zone_record" "test" {
	zone = "mydomain.ovh"
	subdomain = "sub"
	fieldtype = "A"
	ttl = "3600"
	target = "192.168.1.1"
}
```

### Debug Output
[https://gist.github.com/wattshout/6dea68809569b7f66d4c519a1b1d3a12](https://gist.github.com/wattshout/6dea68809569b7f66d4c519a1b1d3a12)

### Panic Output
n/a

### Expected Behavior
The provider should have been set and the resource should have been checked.

### Actual Behavior
Terraform throws back an error "provider.ovh: unexpected EOF"

### Steps to Reproduce
1. `terraform plan`

### Important Factoids
Tried with provider v0.1.1 which works but doesn't handle ovh_domain_zone_record resources apparently.

### References
Didn't seem to find any information about this on the internets.

**Comment by yanndegat** [comment]
hi @wattshout 

it seems odd.

according to your gist, the error tells that the provider is not impl. for linux/amd64
yet it is.

one question: have you run the "terraform init" command when you upgraded to v0.2.0?
the init command is now required by terraform, it will download all required plugins and modules in the working_dir/.terraform directory.

**Comment by wattshout** [comment]
hi @yanndegat, thanks for your answer.

I did run the "terraform init" command before that, and it's been found by terraform as you can check from the [gist](https://gist.github.com/wattshout/6dea68809569b7f66d4c519a1b1d3a12#file-gistfile1-txt-L15) i've attached.

**Comment by yanndegat** [comment]
right,
but near the end of the log, you have this line.

its quite odd because i use the 0.2.0 provider on a day to day basis, on
linux, and i never hit this issue

2018-01-28T10:38:28.232Z [DEBUG] plugin.terraform-provider-ovh_v0.2.0_x4:
2018/01/28 10:38:28 user: Current not implemented on linux/amd64



-yann

**Comment by thbkrkr** [comment]
I spotted another place that uses user.Current(): https://github.com/terraform-providers/terraform-provider-ovh/blob/master/ovh/provider.go#L76. We can fix it as for go-ovh: https://github.com/ovh/go-ovh/commit/34b9ffdf98692f9e9b57724d180549f88725b605.
