### ISSUE TITLE
Reflect API path in resource naming

### ISSUE THREAD

**Issue by goblain** [terraform-providers/terraform-provider-ovh#23]
It would seem reasonable to keep names of resources a bit more in line with what can be found in OVH API. 
For example, considering the URI in OVH API is 
`/cloud/project/{serviceName}/network/private/{networkId}/subnet`
the resource name for private networks subnet would be
`ovh_cloud_network_private_subnet` 
instead of 
`ovh_publiccloud_private_network_subnet`

I could adapt that keeping previous naming for backward compatibility. It would also provide a clear guideline on how to name new resources.

**Comment by yanndegat** [comment]
released
