### ISSUE TITLE
Partial web documentation compared to Github sources

### ISSUE THREAD

**Issue by dlecan** [terraform-providers/terraform-provider-ovh#24]
I was lookup for information about dns resources of OVH provider.

I found `resource_ovh_dns_record.go` and [its documentation](https://github.com/terraform-providers/terraform-provider-ovh/blob/master/website/docs/r/ovh_domain_zone_record.html.markdown) but no link from the [official web documentation](https://www.terraform.io/docs/providers/ovh/index.html).

### Expected Behavior
Documentation about dns resources on https://www.terraform.io/docs/providers/ovh/index.html

### Actual Behavior
Nothing about dns resources on https://www.terraform.io/docs/providers/ovh/index.html

### Steps to Reproduce
Go to https://www.terraform.io/docs/providers/ovh/index.html :-)

**Comment by dlecan** [comment]
@yanndegat is it possible to trigger a redeployment of the website?

**Comment by yanndegat** [comment]
released
