### ISSUE TITLE
Enhancement: resource for redirection

### ISSUE THREAD

**Issue by dlecan** [terraform-providers/terraform-provider-ovh#30]
I already use OVH provider to manage my domains, that works fine, except redirections are missing.

As I would like to work on this, I would be sure to work in the right direction:
- I will use this API documentation: https://api.ovh.com/console/#/domain/zone/%7BzoneName%7D/redirection/%7Bid%7D#GET
- I will use `resource_ovh_domain_zone_record.go` as a sample for structuring the code
- Same thing for tests

I think I won't be able to execute acceptance tests.

Is it ok for you?

**Comment by yanndegat** [comment]
hi @dlecan 

yes of course

that would be very great

thanks a lot for spending time on this

**Comment by dlecan** [comment]
@yanndegat 
I'm writing documentation about redirections, and I think 2 features overlap between records and redirections: CNAME and invisible redirections (more, apex A record is already defined by invisible redirections).

Should I advise to use invisible redirections instead of CNAME in the documentation?

**Comment by yanndegat** [comment]
closed by #36
