### ISSUE TITLE
Bump version and generate new release

### ISSUE THREAD

**Issue by cortexx** [terraform-providers/terraform-provider-ovh#85]
Hi everyone,

After some tests with the OVH provider, I take few minutes to open this issue.
It's not an usual issue opened to implement new feature or debugging some stuff, it's an issue to check with the maintainers of this repository if it's possible to generate a new release of this Terraform provider.

I have spent some time to debug the usage of the `ovh_cloud_network_private` resource to import some existing objects in my `.tfstate` file without understanding why it didn't work.

I worked with the following declaration in my p`provider.tf` file:
```hcl
provider "ovh" {
  version = "0.3.0"
  endpoint = "ovh-eu"
}
```

After discuss with @yanndegat, he advices me to build the provider in my Go environment and to rerun my code. And this was the solution's of all my problem ^^ 

What is the step to ask properly new release regularly ? 
It's possible to implement a workflow to generate automatically new release of this provider ? 

### Terraform Version
```shell
terraform --version
Terraform v0.11.13
```
### Affected Resource(s)
At least, I haven't yet test other resource: 
- ovh_cloud_network_private

### Actual Behavior
With the provider based on the `0.3.0` release tag:
```shell
import module.import.ovh_cloud_network_private.test1
result: xxxxxxxxx: ovh_cloud_network_private.test1: Error calling /cloud/project/xxxxxxxx/network/private/xxxxxxxxx:
         "Error 404: \"The requested network (id = xxxxxxxxx) does not exist\""
```

### Expected Behavior
With the provider based on the last commit of this code repository:
```shell
Import successful!
```

/thanks for your work :)

**Comment by yanndegat** [comment]
solved by last release. thanks
